kind: Secret
apiVersion: v1
metadata:
  name: {{ include "es2loki.fullname" . }}-config
  labels:
    {{- include "es2loki.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
