apiVersion: v1
kind: Secret
metadata:
  name: {{ include "selectel-exporter.fullname" . }}
  labels:
    {{- include "selectel-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  password: "{{ .Values.selectel.token | b64enc }}"
