apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse-bulk.fullname" . }}-config
  labels:
    {{- include "clickhouse-bulk.labels" . | nindent 4 }}
data:
  config.json: |
    {
        "listen": ":8124",
        "flush_count": 10000,
        "flush_interval": 1000,
        "clean_interval": 0,
        "remove_query_id": true,
        "dump_check_interval": 300,
        "debug": false,
        "dump_dir": "/dumps",
        "clickhouse": {
            "down_timeout": 60,
            "connect_timeout": 10,
            "tls_server_name": "",
            "insecure_tls_skip_verify": false,
            "servers": [
                "http://127.0.0.1:8123"
            ]
        },
        "use_tls": false,
        "tls_cert_file": "",
        "tls_key_file": ""
    }
