{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "clickhouse-bulk.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace | quote }}
  {{- end }}
  labels:
    {{- include "clickhouse-bulk.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "clickhouse-bulk.labels" . | nindent 6 }}
  {{- if .Values.serviceMonitor.targetLabels }}
  targetLabels:
  {{- range .Values.serviceMonitor.targetLabels }}
    - {{ . }}
  {{- end }}
  {{- end }}
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.scrapeInterval }}
    {{- if .Values.serviceMonitor.honorLabels }}
    honorLabels: true
    {{- end }}
    {{- if .Values.serviceMonitor.relabelings }}
    relabelings: {{ toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
    {{- end }}
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings: {{ toYaml .Values.serviceMonitor.metricRelabelings | nindent 8 }}
    {{- end }}
{{- end }}