apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clickhouse-bulk.fullname" . }}
  labels:
    {{- include "clickhouse-bulk.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "clickhouse-bulk.selectorLabels" . | nindent 6 }}
  serviceName: "{{ include "clickhouse-bulk.fullname" . }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clickhouse-bulk.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clickhouse-bulk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - ./clickhouse-bulk
            - -config=/etc/clickhouse-bulk/config.json
          ports:
            - name: http
              containerPort: 8124
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CLICKHOUSE_BULK_DEBUG
              value: {{ .Values.config.debug | quote }}
            - name: CLICKHOUSE_FLUSH_COUNT
              value: {{ .Values.config.flushCount | quote }}
            - name: CLICKHOUSE_FLUSH_INTERVAL
              value: {{ .Values.config.flushInterval | quote }}
            - name: CLICKHOUSE_CLEAN_INTERVAL
              value: {{ .Values.config.cleanInterval | quote }}
            - name: CLICKHOUSE_REMOVE_QUERY_ID
              value: {{ .Values.config.removeQueryId | quote }}
            - name: DUMP_CHECK_INTERVAL
              value: {{ .Values.config.dumpCheckInterval | quote }}
            - name: CLICKHOUSE_DOWN_TIMEOUT
              value: {{ .Values.config.clickhouse.downTimeout | quote }}
            - name: CLICKHOUSE_CONNECT_TIMEOUT
              value: {{ .Values.config.clickhouse.connectTimeout | quote }}
            - name: CLICKHOUSE_INSECURE_TLS_SKIP_VERIFY
              value: {{ .Values.config.clickhouse.insecureTlsSkipVerify | quote }}
            - name: METRICS_PREFIX
              value: {{ .Values.config.metricsPrefix | quote }}
            - name: CLICKHOUSE_SERVERS
              value: {{ .Values.config.clickhouse.servers | quote }}
            - name: CLICKHOUSE_TLS_SERVER_NAME
              value: {{ .Values.config.clickhouse.tlsServerName | quote }}
          volumeMounts:
            - name: config
              mountPath: /etc/clickhouse-bulk
              readOnly: true
            - name: dumps
              mountPath: /dumps
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "clickhouse-bulk.fullname" . }}-config
        {{- if not .Values.persistence.enabled }}
        - name: dumps
          emptyDir: {}
        {{- end }}
  {{- if and .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: dumps
        annotations:
        {{- range $key, $value := .Values.persistence.annotations }}
          {{ $key }}: {{ $value }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.storageClass -}}
        {{- if (eq "-" .Values.persistence.storageClass) -}}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end -}}
        {{- end -}}
        {{- with .Values.persistence.selector }}
        selector: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- end }}