apiVersion: v2
name: es2loki
description: Elasticsearch to Grafana Loki logs transfer library
type: application
version: 1.0.1
appVersion: "0.1.6"
dependencies:
- name: postgresql
  version: "12.1.3"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
